title = "cmaugustine"
base_url = "https://cmaugustine.github.io/"
compile_sass = true
highlight_code = true
highlight_theme = "charcoal"
theme = "after-dark"

taxonomies = [
    {name = "aux", rss = true},
]

[extra]
after_dark_title = cmaugustine

after_dark_menu = [
    {url = "$BASE_URL, name = "home"},
    {url = "$BASE_URL/blog, name = "blog"},
    {url = "$BASE_URL/aux, name = "home"},
    {url = "$BASE_URL/about, name = "home"},


# Put all your custom variables here
